### ISSUE TITLE
Got error: 'KeyedListSerializer' is not defined

### ISSUE THREAD

**Issue by taime** [claytondaley/drf-keyed-list#7]
I follow the example in docs, and get error:
`name 'KeyedListSerializer' is not defined`

Could you please give an instruction, how to use this library?

**Comment by claytondaley** [comment]
If you pip installed it, you should be able to import it from `drf_keyed_list`.  If that's not working, please give me more information about your environment.

**Comment by sshishov** [comment]
@taime you got this error because you forgot to import the serializer.
@claytondaley, I think that we should put the import inside the README file to avoid such situation. When users who are not close familiar with python using the library, they just want copy-paste the code and do not want to understand the internals and import dependencies.

```python
from drf_keyed_list import KeyedListSerializer


class MySerializer(ModelSerializer):

    class Meta:
        list_serializer_class = KeyedListSerializer
        keyed_list_serializer_field = 'id'
```

What do you think?

**Comment by claytondaley** [comment]
Sure.  That's fine.

**Comment by claytondaley** [comment]
... also commented out the ellipsis so the code should be valid for cut-paste.
